adminapp/urls.py
from django.urls import path
from .views import index, admin_users_read, admin_users_create, admin_users_update, admin_users_delete, \
    admin_category_read, admin_category_create, admin_category_update, admin_category_delete

app_name = 'adminapp'
urlpatterns = [
    path('', index, name='index'),

    path('users/', admin_users_read, name='admin_users_read'),
    path('users/create/', admin_users_create, name='admin_users_create'),
    path('users/update/<int:id>', admin_users_update, name='admin_users_update'),
    path('users/delete/<int:id>', admin_users_delete, name='admin_users_delete'),

    path('category/', admin_category_read, name='admin_category_read'),
    path('category/create/', admin_category_create, name='admin_category_create'),
    path('category/update/<int:id>/', admin_category_update, name='admin_category_update'),
    path('category/delete/<int:id>/', admin_category_delete, name='admin_category_delete'),

]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import login, registration, logout, profile

app_name = 'users'
urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from users.forms import UserRegistrationForm, UserProfileForm
from users.models import User
from products.models import ProductCategory


class UserAdminRegistrationForm(UserRegistrationForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'custom-file-input',
    }), required=False)

    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'email', 'password1', 'password2', 'image')


class UserAdminProfileForm(UserProfileForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
    }))


class AdminProductCategory(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ['name', 'description', ]

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test
# Create your views here.
from users.models import User
from products.models import ProductCategory
from adminapp.forms import UserAdminRegistrationForm, UserAdminProfileForm, AdminProductCategory


@user_passes_test(lambda u: u.is_staff)
def index(request):
    context = {
        'title': 'Админ панель',
    }
    return render(request, './adminapp/index.html', context)

######################################################################
@user_passes_test(lambda u: u.is_staff)
def admin_users_read(request):
    context = {
        'title': 'Админ панель - пользователи',
        'users': User.objects.all()
    }
    return render(request, './adminapp/admin-users-read.html', context)


@user_passes_test(lambda u: u.is_staff)
def admin_users_create(request):
    if request.method == 'POST':
        form = UserAdminRegistrationForm(files=request.FILES, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:admin_users_read'))
    else:
        form = UserAdminRegistrationForm()

    context = {
        'title': 'Админ панель -  создание пользователя',
        'form': form
    }
    return render(request, './adminapp/admin-users-create.html', context)


@user_passes_test(lambda u: u.is_staff)
def admin_users_delete(request, id):
    user = User.objects.get(pk=id)
    user.delete()
    return HttpResponseRedirect(reverse('adminapp:admin_users_read'))


@user_passes_test(lambda u: u.is_staff)
def admin_users_update(request, id):
    selected_user = User.objects.get(pk=id)
    if request.method == 'POST':
        form = UserAdminProfileForm(instance=selected_user, files=request.FILES, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:admin_users_read'))
    else:
        form = UserAdminProfileForm(instance=selected_user)
    context = {
        'title': 'Админ панель -  редактирование пользователя',
        'form': form,
        'selected_user': selected_user,
    }
    return render(request, './adminapp/admin-users-update-delete.html', context)


######################################################################
@user_passes_test(lambda u: u.is_staff)
def admin_category_read(request):
    context = {
        'title': 'Админ панель - категории',
        'categories': ProductCategory.objects.filter(deleted_at=None)
    }
    return render(request, './adminapp/admin-category-read.html', context)


@user_passes_test(lambda u: u.is_staff)
def admin_category_create(request):
    if request.method == 'POST':
        form = AdminProductCategory(files=request.FILES, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:admin_category_read'))
    else:
        form = AdminProductCategory()

    context = {
        'title': 'Админ панель -  создание категории',
        'form': form
    }
    return render(request, './adminapp/admin-category-create.html', context)


@user_passes_test(lambda u: u.is_staff)
def admin_category_update(request, id):
    selected_category = ProductCategory.objects.get(pk=id)
    if request.method == 'POST':
        form = AdminProductCategory(instance=selected_category, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminapp:admin_category_read'))
    else:
        form = AdminProductCategory(instance=selected_category)
    context = {
        'title': 'Админ панель -  редактирование категории',
        'form': form,
        'selected_category': selected_category,
    }
    return render(request, './adminapp/admin-category-update-delete.html', context)


@user_passes_test(lambda u: u.is_staff)
def admin_category_delete(request, id):
    category = ProductCategory.objects.get(pk=id, deleted_at=None)
    category.delete()
    return HttpResponseRedirect(reverse('adminapp:admin_category_read'))
######################################################################

adminapp/templates/adminapp/admin-category-create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="container-fluid">
            <h1 class="mt-4">Создание категории</h1>
            <form action="{% url 'adminapp:admin_category_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Имя категории</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание
                                категории</label>
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

adminapp/templates/adminapp/admin-category-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя категории</th>
                                <th>Описание категории</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя категории</th>
                                <th>Описание категории</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in categories %}
                                <tr>
                                    <td><a href="{% url 'adminapp:admin_category_update' category.pk %}"
                                           style="color: dodgerblue">{{ category.name }}</a></td>
                                    <td>{{ category.description }}</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:admin_category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

adminapp/templates/adminapp/admin-category-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование пользователя | {{ selected_category.name }}</h1>
            <div class="card-body">
                <form action="{% url 'adminapp:admin_category_update' selected_category.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Имя</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Фамилия</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <a class="btn btn-danger btn-block"
                           href="{% url 'adminapp:admin_category_delete' selected_category.id %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

adminapp/templates/adminapp/admin-users-create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="container-fluid">
            <h1 class="mt-4">Создание пользователя</h1>
            <form action="{% url 'adminapp:admin_users_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.image }}
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                        {{ form.password1 }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Пользователи
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for user in users %}
                                <tr>
                                    <td><a href="{% url 'adminapp:admin_users_update' user.pk %}"
                                           style="color: dodgerblue">{{ user.username }}</a></td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    {% if user.is_stuff %}
                                        <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                    {% else %}
                                        <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                    {% if user.is_active %}
                                        <td class="text-center"><i class="fas fa-check-circle"></i></td>
                                    {% else %}
                                        <td class="text-center"><i class="fas fa-times-circle"></i></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:admin_users_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование пользователя | {{ selected_user.username }}</h1>
            <div class="card-body">
                <form action="{% url 'adminapp:admin_users_update' selected_user.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <a class="btn btn-danger btn-block"
                           href="{% url 'adminapp:admin_users_delete' selected_user.id %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

adminapp/templates/adminapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Admin</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'adminapp:index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'adminapp:admin_users_read' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'adminapp:admin_category_read' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="index.html">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        {% block content %}

        {% endblock content %}
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2020</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Административная панель</h1>

        </div>
    </main>
{% endblock content %}